In [1]:
import torch

In [2]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/Size: {}".format(x.shape))
    print("Values: \n{}".format(x))

In [3]:
describe(torch.Tensor(2,3))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[-1.5733e+27,  4.5639e-41, -2.2220e+25],
        [ 3.0858e-41,  4.4842e-44,  0.0000e+00]])


In [4]:
describe(torch.rand(2,3))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0.4683, 0.5441, 0.2595],
        [0.1228, 0.9832, 0.0964]])


In [5]:
describe(torch.randn(2,3))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[ 0.7601,  1.1644,  0.5759],
        [ 0.0133, -0.0922, -0.4370]])


In [6]:
describe(torch.zeros(2,3))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
x = torch.ones(2,3)

In [8]:
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [9]:
x.fill_(5)

tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [10]:
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [11]:
x = torch.Tensor([[1, 2, 3],
                  [4, 5, 6]])

In [12]:
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [13]:
import numpy as np

In [14]:
npy = np.random.rand(2, 3)

In [15]:
describe(torch.from_numpy(npy))

Type: torch.DoubleTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0.9001, 0.8592, 0.5332],
        [0.3863, 0.9784, 0.5244]], dtype=torch.float64)


In [16]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])

In [17]:
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [18]:
x = x.long()

In [19]:
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [20]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], dtype = torch.int16)

In [21]:
describe(x)

Type: torch.ShortTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int16)


In [22]:
x = x.float()

In [23]:
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [24]:
x = torch.randn(2, 3)

In [25]:
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[ 0.6705,  0.2468, -1.1223],
        [ 0.0383, -0.4235, -0.8055]])


In [26]:
describe(torch.add(x, x))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[ 1.3411,  0.4935, -2.2446],
        [ 0.0765, -0.8470, -1.6109]])


In [27]:
describe(x + x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[ 1.3411,  0.4935, -2.2446],
        [ 0.0765, -0.8470, -1.6109]])


In [28]:
x = torch.arange(6)

In [29]:
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [30]:
x = x.view(2, 3)

In [31]:
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [32]:
describe(torch.sum(x, dim=0))

Type: torch.LongTensor
Shape/Size: torch.Size([3])
Values: 
tensor([3, 5, 7])


In [33]:
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [34]:
describe(torch.sum(x, dim=1))

Type: torch.LongTensor
Shape/Size: torch.Size([2])
Values: 
tensor([ 3, 12])
